Merging AppGroup changes into 2.x branch (#869)
* Checking if the organisation is ApigeeX for AppGroup (#803)

* Fix organisation exception (#806)

* Changes for Appgroup listing/view/edit/delete page (#805)

* Changes for Appgroup listing/view/edit/delete page

* Update composer.json

* Update composer.json

* AppGroup-App implementation for list, view, edit, delete apps (#813)

* Merge 2.x into appgroup (#829)

* Warrant that queues executed by cron (#808)

* Sort API Product listings on App (#812)

* Update endpoints to use constants from ClientInterface (#810)

* Sort API products on app forms by API product display name (#815)

* Sort API Products (#818)

* Sort API Products
TypeError: array_map(): Argument #2 ($array) must be of type array

* Removed test case

* App creation fails without API Products (#809)

* App creation fails without API Products caused by features.keymanagement.disable.unbounded.permissions flag
* Update minimum version of apigee-client-php

* Make sure that cron runner starts executing the job (#814)

* Checking if the organisation is ApigeeX for AppGroup (#803)

* Fix organisation exception (#806)

* Changes for Appgroup listing/view/edit/delete page (#805)

* Changes for Appgroup listing/view/edit/delete page

* Update composer.json

* Update composer.json

* AppGroup-App implementation for list, view, edit, delete apps (#813)

---------

Co-authored-by: Dezső BICZÓ <mxr576@users.noreply.github.com>
Co-authored-by: Shishir <75600200+shishir-intelli@users.noreply.github.com>
Co-authored-by: phdhiren <hirenkumar@google.com>
Co-authored-by: Divyajose <75604843+divya-intelli@users.noreply.github.com>

* Support for Add AppGroup/team and update team App credentials with ApiProduct (#824)

* Support for AppGroup membership (#825)

* The Apigee Edge and X Teams module requirements (#826)

* Checking ApigeeX org from OrganizationController and removed from SDKController (#832)

* If team not available on Apigee avoid null value exception (#833)

* Added admin config setting for Team prefix and channelID (#839)

* Implemented AppGroup membership feature for ApigeeX (#843)

* Merge 2.x into appgroup branch (#859)

* Warrant that queues executed by cron (#808)

* Sort API Product listings on App (#812)

* Update endpoints to use constants from ClientInterface (#810)

* Sort API products on app forms by API product display name (#815)

* Sort API Products (#818)

* Sort API Products
TypeError: array_map(): Argument #2 ($array) must be of type array

* Removed test case

* App creation fails without API Products (#809)

* App creation fails without API Products caused by features.keymanagement.disable.unbounded.permissions flag
* Update minimum version of apigee-client-php

* Make sure that cron runner starts executing the job (#814)

* Update the storage defination of App entity (#831)

* Fix issue which removes users from all team (#840)

* Drop PHP 7 support again (#816)

* Revert "Support for PHP 7.4 (#800)"

This reverts commit b71f8a9cebc4fcdf9f0dc447d92f3ed6ea6173a7.

* Clearly specify the currently supported PHP versions

* Update outdated info.yml

* Added accessCheck on entity queries (#842)

* added accessCheck on entity queries

Co-authored-by: Vladimir Roudakov <VladimirAus@users.noreply.github.com>

* added comment

---------

Co-authored-by: Vladimir Roudakov <VladimirAus@users.noreply.github.com>

* Fix for jQuery.once() is deprecated in Drupal 9.3 (#851)

Co-authored-by: Vladimir Roudakov <VladimirAus@users.noreply.github.com>

* fix for phpcs failing in github action (#858)

* PHPCS FIX

---------
Co-authored-by: Shishir <75600200+shishir-intelli@users.noreply.github.com>
Co-authored-by: Dezső BICZÓ <mxr576@users.noreply.github.com>
Co-authored-by: Gitesh Koli <giteshk@users.noreply.github.com>
Co-authored-by: Divyajose <75604843+divya-intelli@users.noreply.github.com>
Co-authored-by: Vladimir Roudakov <VladimirAus@users.noreply.github.com>

* Implemented AppGroup Team Membership Sync (#853)

* Get AppGroup team members from DB (#864)

* Get AppGroup team members from DB and fix recurring teams api call

* Declaring abstract method

* Fix action module getTeam method argument

* Fix for team sync issue when DB is empty

* Added team member sync note for ApigeeX (#867)

---------

Co-authored-by: Shishir <75600200+shishir-intelli@users.noreply.github.com>
Co-authored-by: Divyajose <75604843+divya-intelli@users.noreply.github.com>
Co-authored-by: Gitesh Koli <giteshk@users.noreply.github.com>
Co-authored-by: Dezső BICZÓ <mxr576@users.noreply.github.com>
Co-authored-by: Vladimir Roudakov <VladimirAus@users.noreply.github.com>